### ISSUE TITLE
Paladin starting spells

### ISSUE THREAD

**Issue by Enzantel** [ThanokKarabor/Karabor#8]
Paladin: Starting with 2 Seal of Righteousness in spellbook (all races)

https://ibb.co/mciXWF

**Comment by Azmodeane** [comment]
I can confirm this

**Comment by Azmodeane** [comment]
Furthermore, inspection of the spells shows that one of the Seals does not have a "Judgement" clause, as it should. Applying the Seal to myself and Judgementing it will cause the animation and CD to trigger; however, it does not damage teh creature or register in the Combat Log. Complete removal of this second spell should resolve issue, since the first one is working perfectly.

SS:
![judgement clause missing](https://cloud.githubusercontent.com/assets/20554265/24223918/a80b92ca-0f15-11e7-9216-d5c1be34bf44.jpg)

**Comment by ThanokKarabor** [comment]
Deleted the redundant seal of Righteousness, works good now 👍
